#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Changes MAC Address on boot
### END INIT INFO

INTERFACE="wlan0"

change_mac()
{
  curr_mac=`cat /sys/class/net/$INTERFACE/address`
  sudo ip link set $INTERFACE down
  sudo macchanger -A $INTERFACE >> /dev/null 2>&1
  sudo ip link set $INTERFACE up
  service network-manager restart >> /dev/null 2>&1
  new_mac=`cat /sys/class/net/$INTERFACE/address`
  if [ "\$curr_mac" != "\$new_mac" ]
  then
    echo "MAC Address Changed Succefully"
    exit 0
  else
    echo "Unable Change MAC Address"
    exit 1
  fi
}

restore_mac()
{
  sudo ip link set $INTERFACE down
  macchanger -p $INTERFACE >> /dev/null 2>&1
  echo "MAC Address Restored "`cat /sys/class/net/$INTERFACE/address`
  sudo ip link set $INTERFACE up
  service network-manager restart >> /dev/null 2>&1
  exit 0
}

case "$1" in
    start)
      change_mac # Execuites at the time of boot!
    ;;
	new)
      change_mac
    ;;
    restore)
      restore_mac
    ;;
    show)
      echo "Current MAC: "`cat /sys/class/net/$INTERFACE/address`
      exit 0
    ;;
esac
