#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

name="dnscrypt-proxy"
pid_file="/var/run/dnscrypt-proxy.pid"
log="/var/log/dnscrypt-proxy.log "

csv_file="/opt/dnscrypt-resolvers.csv"
resolver_name="soltysiak"

if [ -f "csv_file" ]
then
    echo "dnscrypt-resolvers.csv not found"
    exit 1
fi

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "$name already running"
    else
        echo "Starting $name"
        sudo dnscrypt-proxy -R $resolver_name -L $csv_file -l $log -p $pid_file -d > /dev/null 2>&1
        if ! is_running; then
            echo "Unable to start, see $log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo "Stopping $name.."
        sudo kill -9 `get_pid`
    else
        echo "$name is not running"
    fi
    ;;
    restart)
    stop
    start
    ;;
    status)
    if is_running; then
        echo "$name running"
    else
        echo "$name stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
